import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Nebula Velvet Sofa',
    price: 1299,
    category: 'Living Room',
    description: 'A luxurious deep blue velvet sofa with mid-century modern tapered legs. Perfect for lounging in style.',
    image: 'https://picsum.photos/seed/sofa1/800/600',
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Oak Minimalist Desk',
    price: 450,
    category: 'Office',
    description: 'Solid oak desk with a clean, Scandinavian design. Features two discreet drawers for storage.',
    image: 'https://picsum.photos/seed/desk1/800/600',
    rating: 4.5,
  },
  {
    id: '3',
    name: 'Luna Pendant Light',
    price: 180,
    category: 'Lighting',
    description: 'A spherical pendant light with a brass finish. Adds a warm, ambient glow to any dining area.',
    image: 'https://picsum.photos/seed/light1/800/600',
    rating: 4.9,
  },
  {
    id: '4',
    name: 'Terra Cotta Vase Set',
    price: 85,
    category: 'Living Room',
    description: 'Hand-crafted terracotta vases in varying sizes. Adds an organic, earthy touch to your shelves.',
    image: 'https://picsum.photos/seed/vase1/800/600',
    rating: 4.2,
  },
  {
    id: '5',
    name: 'Cloud Soft Armchair',
    price: 599,
    category: 'Living Room',
    description: 'An overstuffed white boucle armchair that feels like sitting on a cloud. Extremely comfortable.',
    image: 'https://picsum.photos/seed/chair1/800/600',
    rating: 4.7,
  },
  {
    id: '6',
    name: 'Midnight Bed Frame',
    price: 899,
    category: 'Bedroom',
    description: 'Black metal bed frame with an industrial chic aesthetic. Sturdy and silent construction.',
    image: 'https://picsum.photos/seed/bed1/800/600',
    rating: 4.6,
  },
  {
    id: '7',
    name: 'Teak Dining Table',
    price: 1400,
    category: 'Dining',
    description: 'Reclaimed teak wood dining table. Seats 6 people comfortably. Weathered finish.',
    image: 'https://picsum.photos/seed/table1/800/600',
    rating: 4.8,
  },
  {
    id: '8',
    name: 'Ergo Office Chair',
    price: 350,
    category: 'Office',
    description: 'High-performance ergonomic chair with breathable mesh back and adjustable lumbar support.',
    image: 'https://picsum.photos/seed/chair2/800/600',
    rating: 4.4,
  },
];
